# Generated by Django 5.2.7 on 2025-10-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0002_analyticsproduct_product_productview_shop_shopview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='analyticsproduct',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='productview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shopview',
            name='shop',
        ),
        migrations.AddField(
            model_name='analyticsproduct',
            name='product_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsproduct',
            name='shop_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productview',
            name='product_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopview',
            name='shop_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyticsproduct',
            name='product_variation_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
