# Generated by Django 5.2.7 on 2025-10-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0003_remove_analyticsproduct_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
