# Generated by Django 5.2.7 on 2025-10-06 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0004_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticsproduct',
            old_name='created_at',
            new_name='viewed_at',
        ),
        migrations.RemoveField(
            model_name='analyticsproduct',
            name='count',
        ),
        migrations.RemoveField(
            model_name='analyticsproduct',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='analyticsproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='analyticsproduct',
            name='product_variation_id',
        ),
        migrations.RemoveField(
            model_name='analyticsproduct',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='analyticsproduct',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='productview',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='shopview',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='analyticsproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics_app.product'),
        ),
        migrations.AddField(
            model_name='analyticsproduct',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics_app.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics_app.product'),
        ),
        migrations.AddField(
            model_name='shopview',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics_app.shop'),
        ),
    ]
