# Generated by Django 5.2.7 on 2025-10-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0005_rename_created_at_analyticsproduct_viewed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticsproduct',
            old_name='viewed_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='analyticsproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='analyticsproduct',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsproduct',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticsproduct',
            name='product_variation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='analytics_app.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticsproduct',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsproduct',
            name='shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='analytics_app.shop'),
            preserve_default=False,
        ),
    ]
